remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "dirt"
title: "LCP"
title_separator: "-"

inlcude: ["_pages"]

paginate: 5 # amount of posts to show
paginate_path: /blog/page:num/ 

